# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chalk/common/v1/chart.proto

require 'google/protobuf'


descriptor_data = "\n\x1b\x63halk/common/v1/chart.proto\x12\x0f\x63halk.common.v1\"P\n\x06Series\x12\x16\n\x06points\x18\x01 \x03(\x01R\x06points\x12\x14\n\x05label\x18\x02 \x01(\tR\x05label\x12\x14\n\x05units\x18\x03 \x01(\tR\x05units:\x02\x18\x01\"x\n\x05\x43hart\x12\x14\n\x05title\x18\x01 \x01(\tR\x05title\x12/\n\x06series\x18\x02 \x03(\x0b\x32\x17.chalk.common.v1.SeriesR\x06series\x12$\n\x0ex_timestamp_ms\x18\x04 \x03(\x03R\x0cxTimestampMs:\x02\x18\x01\x42\x7f\n\x13\x63om.chalk.common.v1B\nChartProtoP\x01\xa2\x02\x03\x43\x43X\xaa\x02\x0f\x43halk.Common.V1\xca\x02\x0f\x43halk\\Common\\V1\xe2\x02\x1b\x43halk\\Common\\V1\\GPBMetadata\xea\x02\x11\x43halk::Common::V1b\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Chalk
  module Common
    module V1
      Series = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chalk.common.v1.Series").msgclass
      Chart = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chalk.common.v1.Chart").msgclass
    end
  end
end
