# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chalk/common/v1/operation_kind.proto

require 'google/protobuf'


descriptor_data = "\n$chalk/common/v1/operation_kind.proto\x12\x0f\x63halk.common.v1*\x94\x02\n\rOperationKind\x12\x1e\n\x1aOPERATION_KIND_UNSPECIFIED\x10\x00\x12\x1f\n\x1bOPERATION_KIND_ONLINE_QUERY\x10\x01\x12\x1c\n\x18OPERATION_KIND_MIGRATION\x10\x02\x12\x17\n\x13OPERATION_KIND_CRON\x10\x03\x12\x1c\n\x18OPERATION_KIND_STREAMING\x10\x04\x12$\n OPERATION_KIND_MIGRATION_SAMPLER\x10\x05\x12%\n!OPERATION_KIND_WINDOWED_STREAMING\x10\x06\x12 \n\x1cOPERATION_KIND_OFFLINE_QUERY\x10\x07\x42\x87\x01\n\x13\x63om.chalk.common.v1B\x12OperationKindProtoP\x01\xa2\x02\x03\x43\x43X\xaa\x02\x0f\x43halk.Common.V1\xca\x02\x0f\x43halk\\Common\\V1\xe2\x02\x1b\x43halk\\Common\\V1\\GPBMetadata\xea\x02\x11\x43halk::Common::V1b\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Chalk
  module Common
    module V1
      OperationKind = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chalk.common.v1.OperationKind").enummodule
    end
  end
end
