# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chalk/common/v1/query_status.proto

require 'google/protobuf'


descriptor_data = "\n\"chalk/common/v1/query_status.proto\x12\x0f\x63halk.common.v1*\xa3\x02\n\x0bQueryStatus\x12\x1c\n\x18QUERY_STATUS_UNSPECIFIED\x10\x00\x12#\n\x1fQUERY_STATUS_PENDING_SUBMISSION\x10\x01\x12\x1a\n\x16QUERY_STATUS_SUBMITTED\x10\x02\x12\x18\n\x14QUERY_STATUS_RUNNING\x10\x03\x12\x16\n\x12QUERY_STATUS_ERROR\x10\x04\x12\x18\n\x14QUERY_STATUS_EXPIRED\x10\x05\x12\x1a\n\x16QUERY_STATUS_CANCELLED\x10\x06\x12\x1b\n\x17QUERY_STATUS_SUCCESSFUL\x10\x07\x12\x30\n,QUERY_STATUS_SUCCESSFUL_WITH_NONFATAL_ERRORS\x10\x08\x42}\n\x13\x63om.chalk.common.v1B\x10QueryStatusProtoP\x01\xa2\x02\x03\x43\x43X\xaa\x02\x0f\x43halk.Common.V1\xca\x02\x0f\x43halk\\Common\\V1\xe2\x02\x1b\x43halk\\Common\\V1\\GPBMetadata\xea\x02\tChalkRubyb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module ChalkRuby
  QueryStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chalk.common.v1.QueryStatus").enummodule
end
