# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chalk/engine/v1/offline_store_service.proto

require 'google/protobuf'

require 'chalk/auth/v1/permissions_pb'
require 'chalk/common/v1/feature_values_pb'
require 'chalk/common/v1/query_log_pb'
require 'chalk/common/v1/query_values_pb'


descriptor_data = "\n+chalk/engine/v1/offline_store_service.proto\x12\x0f\x63halk.engine.v1\x1a\x1f\x63halk/auth/v1/permissions.proto\x1a$chalk/common/v1/feature_values.proto\x1a\x1f\x63halk/common/v1/query_log.proto\x1a\"chalk/common/v1/query_values.proto\"\x1a\n\x18OfflineStoreServiceDummy2\xb2\x05\n\x13OfflineStoreService\x12r\n\x12GetQueryLogEntries\x12*.chalk.common.v1.GetQueryLogEntriesRequest\x1a+.chalk.common.v1.GetQueryLogEntriesResponse\"\x03\x80}\x04\x12\x66\n\x0eGetQueryValues\x12&.chalk.common.v1.GetQueryValuesRequest\x1a\'.chalk.common.v1.GetQueryValuesResponse\"\x03\x80}\x04\x12~\n\x15GetFeatureValuesChart\x12-.chalk.common.v1.GetFeatureValuesChartRequest\x1a..chalk.common.v1.GetFeatureValuesChartResponse\"\x06\x88\x02\x01\x80}\x04\x12\x9c\x01\n\x1fGetFeatureValuesTimeSeriesChart\x12\x37.chalk.common.v1.GetFeatureValuesTimeSeriesChartRequest\x1a\x38.chalk.common.v1.GetFeatureValuesTimeSeriesChartResponse\"\x06\x88\x02\x01\x80}\x04\x12\x9f\x01\n!GetFeatureValuesTimeSeriesChartV2\x12\x39.chalk.common.v1.GetFeatureValuesTimeSeriesChartV2Request\x1a:.chalk.common.v1.GetFeatureValuesTimeSeriesChartV2Response\"\x03\x80}\x04\x42\x85\x01\n\x13\x63om.chalk.engine.v1B\x18OfflineStoreServiceProtoP\x01\xa2\x02\x03\x43\x45X\xaa\x02\x0f\x43halk.Engine.V1\xca\x02\x0f\x43halk\\Engine\\V1\xe2\x02\x1b\x43halk\\Engine\\V1\\GPBMetadata\xea\x02\tChalkRubyb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module ChalkRuby
  OfflineStoreServiceDummy = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chalk.engine.v1.OfflineStoreServiceDummy").msgclass
end
