# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: chalk/engine/v1/offline_store_service.proto for package 'ChalkRuby'

require 'grpc'
require 'chalk/engine/v1/offline_store_service_pb'

module ChalkRuby
  module OfflineStoreService
    # This service exposes endpoints for dealing with the offline store. It should never depend on the python graph.
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'chalk.engine.v1.OfflineStoreService'

      rpc :GetQueryLogEntries, ::ChalkRuby::GetQueryLogEntriesRequest, ::ChalkRuby::GetQueryLogEntriesResponse
      rpc :GetQueryValues, ::ChalkRuby::GetQueryValuesRequest, ::ChalkRuby::GetQueryValuesResponse
      rpc :GetFeatureValuesChart, ::ChalkRuby::GetFeatureValuesChartRequest, ::ChalkRuby::GetFeatureValuesChartResponse
      rpc :GetFeatureValuesTimeSeriesChart, ::ChalkRuby::GetFeatureValuesTimeSeriesChartRequest, ::ChalkRuby::GetFeatureValuesTimeSeriesChartResponse
      rpc :GetFeatureValuesTimeSeriesChartV2, ::ChalkRuby::GetFeatureValuesTimeSeriesChartV2Request, ::ChalkRuby::GetFeatureValuesTimeSeriesChartV2Response
    end

    Stub = Service.rpc_stub_class
  end
end
