# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: chalk/engine/v1/offline_store_service.proto for package 'Chalk.Engine.V1'

require 'grpc'
require 'chalk_ruby/protos/chalk/engine/v1/offline_store_service_pb'

module Chalk
  module Engine
    module V1
      module OfflineStoreService
        # This service exposes endpoints for dealing with the offline store. It should never depend on the python graph.
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'chalk.engine.v1.OfflineStoreService'

          rpc :GetQueryLogEntries, ::Chalk::Common::V1::GetQueryLogEntriesRequest, ::Chalk::Common::V1::GetQueryLogEntriesResponse
          rpc :GetQueryValues, ::Chalk::Common::V1::GetQueryValuesRequest, ::Chalk::Common::V1::GetQueryValuesResponse
          rpc :GetFeatureValuesChart, ::Chalk::Common::V1::GetFeatureValuesChartRequest, ::Chalk::Common::V1::GetFeatureValuesChartResponse
          rpc :GetFeatureValuesTimeSeriesChart, ::Chalk::Common::V1::GetFeatureValuesTimeSeriesChartRequest, ::Chalk::Common::V1::GetFeatureValuesTimeSeriesChartResponse
          rpc :GetFeatureValuesTimeSeriesChartV2, ::Chalk::Common::V1::GetFeatureValuesTimeSeriesChartV2Request, ::Chalk::Common::V1::GetFeatureValuesTimeSeriesChartV2Response
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
