# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: chalk/engine/v1/plan_server.proto for package 'Chalk.Engine.V1'

require 'grpc'
require 'chalk_ruby/protos/chalk/engine/v1/plan_server_pb'

module Chalk
  module Engine
    module V1
      module PlanService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'chalk.engine.v1.PlanService'

          rpc :GetPlan, ::Chalk::Engine::V1::GetPlanRequest, ::Chalk::Engine::V1::GetPlanResponse
          # Fall-back for executing queries on the python engine
          rpc :ExecuteQuery, ::Chalk::Engine::V1::ExecuteQueryRequest, ::Chalk::Engine::V1::ExecuteQueryResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
