# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chalk/engine/v1/query_server.proto

require 'google/protobuf'

require 'chalk/aggregate/v1/service_pb'
require 'chalk/auth/v1/permissions_pb'
require 'chalk/common/v1/online_query_pb'


descriptor_data = "\n\"chalk/engine/v1/query_server.proto\x12\x0f\x63halk.engine.v1\x1a chalk/aggregate/v1/service.proto\x1a\x1f\x63halk/auth/v1/permissions.proto\x1a\"chalk/common/v1/online_query.proto\"\x1f\n\x0bPingRequest\x12\x10\n\x03num\x18\x01 \x01(\x05R\x03num\" \n\x0cPingResponse\x12\x10\n\x03num\x18\x01 \x01(\x05R\x03num2\xfc\x05\n\x0cQueryService\x12K\n\x04Ping\x12\x1c.chalk.engine.v1.PingRequest\x1a\x1d.chalk.engine.v1.PingResponse\"\x06\x90\x02\x01\x80}\x01\x12]\n\x0bOnlineQuery\x12#.chalk.common.v1.OnlineQueryRequest\x1a$.chalk.common.v1.OnlineQueryResponse\"\x03\x80}\x03\x12i\n\x0fOnlineQueryBulk\x12\'.chalk.common.v1.OnlineQueryBulkRequest\x1a(.chalk.common.v1.OnlineQueryBulkResponse\"\x03\x80}\x03\x12l\n\x10OnlineQueryMulti\x12(.chalk.common.v1.OnlineQueryMultiRequest\x1a).chalk.common.v1.OnlineQueryMultiResponse\"\x03\x80}\x03\x12r\n\x12UploadFeaturesBulk\x12*.chalk.common.v1.UploadFeaturesBulkRequest\x1a+.chalk.common.v1.UploadFeaturesBulkResponse\"\x03\x80}\x03\x12\x84\x01\n\x15PlanAggregateBackfill\x12\x30.chalk.aggregate.v1.PlanAggregateBackfillRequest\x1a\x31.chalk.aggregate.v1.PlanAggregateBackfillResponse\"\x06\x90\x02\x01\x80}\x0c\x12l\n\rGetAggregates\x12(.chalk.aggregate.v1.GetAggregatesRequest\x1a).chalk.aggregate.v1.GetAggregatesResponse\"\x06\x90\x02\x01\x80}\x0b\x42}\n\x13\x63om.chalk.engine.v1B\x10QueryServerProtoP\x01\xa2\x02\x03\x43\x45X\xaa\x02\x0f\x43halk.Engine.V1\xca\x02\x0f\x43halk\\Engine\\V1\xe2\x02\x1b\x43halk\\Engine\\V1\\GPBMetadata\xea\x02\tChalkRubyb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module ChalkRuby
  PingRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chalk.engine.v1.PingRequest").msgclass
  PingResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chalk.engine.v1.PingResponse").msgclass
end
