# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chalk/graph/v2/sources.proto

require 'google/protobuf'

require 'google/protobuf/struct_pb'


descriptor_data = "\n\x1c\x63halk/graph/v2/sources.proto\x12\x0e\x63halk.graph.v2\x1a\x1cgoogle/protobuf/struct.proto\"N\n\x17\x44\x61tabaseSourceReference\x12\x1f\n\x0bsource_type\x18\x01 \x01(\tR\nsourceType\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\"\xe0\x01\n\x0e\x44\x61tabaseSource\x12\x1f\n\x0bsource_type\x18\x01 \x01(\tR\nsourceType\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\x12\x45\n\x07options\x18\x03 \x03(\x0b\x32+.chalk.graph.v2.DatabaseSource.OptionsEntryR\x07options\x1aR\n\x0cOptionsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12,\n\x05value\x18\x02 \x01(\x0b\x32\x16.google.protobuf.ValueR\x05value:\x02\x38\x01\"\xc3\x02\n\x13\x44\x61tabaseSourceGroup\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12N\n\x0e\x64\x65\x66\x61ult_source\x18\x02 \x01(\x0b\x32\'.chalk.graph.v2.DatabaseSourceReferenceR\rdefaultSource\x12]\n\x0etagged_sources\x18\x03 \x03(\x0b\x32\x36.chalk.graph.v2.DatabaseSourceGroup.TaggedSourcesEntryR\rtaggedSources\x1ai\n\x12TaggedSourcesEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12=\n\x05value\x18\x02 \x01(\x0b\x32\'.chalk.graph.v2.DatabaseSourceReferenceR\x05value:\x02\x38\x01\"L\n\x15StreamSourceReference\x12\x1f\n\x0bsource_type\x18\x01 \x01(\tR\nsourceType\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\"\xdc\x01\n\x0cStreamSource\x12\x1f\n\x0bsource_type\x18\x01 \x01(\tR\nsourceType\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\x12\x43\n\x07options\x18\x03 \x03(\x0b\x32).chalk.graph.v2.StreamSource.OptionsEntryR\x07options\x1aR\n\x0cOptionsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12,\n\x05value\x18\x02 \x01(\x0b\x32\x16.google.protobuf.ValueR\x05value:\x02\x38\x01\x42|\n\x12\x63om.chalk.graph.v2B\x0cSourcesProtoP\x01\xa2\x02\x03\x43GX\xaa\x02\x0e\x43halk.Graph.V2\xca\x02\x0e\x43halk\\Graph\\V2\xe2\x02\x1a\x43halk\\Graph\\V2\\GPBMetadata\xea\x02\x10\x43halk::Graph::V2b\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Chalk
  module Graph
    module V2
      DatabaseSourceReference = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chalk.graph.v2.DatabaseSourceReference").msgclass
      DatabaseSource = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chalk.graph.v2.DatabaseSource").msgclass
      DatabaseSourceGroup = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chalk.graph.v2.DatabaseSourceGroup").msgclass
      StreamSourceReference = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chalk.graph.v2.StreamSourceReference").msgclass
      StreamSource = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chalk.graph.v2.StreamSource").msgclass
    end
  end
end
