# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: chalk/server/v1/audit.proto for package 'ChalkRuby'

require 'grpc'
require 'chalk/server/v1/audit_pb'

module ChalkRuby
  module AuditService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'chalk.server.v1.AuditService'

      rpc :GetAuditLogs, ::ChalkRuby::GetAuditLogsRequest, ::ChalkRuby::GetAuditLogsResponse
    end

    Stub = Service.rpc_stub_class
  end
end
