# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chalk/server/v1/audit.proto

require 'google/protobuf'

require 'chalk_ruby/protos/chalk/auth/v1/agent_pb'
require 'chalk_ruby/protos/chalk/auth/v1/permissions_pb'
require 'google/protobuf/struct_pb'
require 'google/protobuf/timestamp_pb'
require 'google/rpc/code_pb'


descriptor_data = "\n\x1b\x63halk/server/v1/audit.proto\x12\x0f\x63halk.server.v1\x1a\x19\x63halk/auth/v1/agent.proto\x1a\x1f\x63halk/auth/v1/permissions.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x15google/rpc/code.proto\"\xe2\x04\n\x08\x41uditLog\x12*\n\x05\x61gent\x18\x01 \x01(\x0b\x32\x14.chalk.auth.v1.AgentR\x05\x61gent\x12%\n\x0b\x64\x65scription\x18\x02 \x01(\tH\x00R\x0b\x64\x65scription\x88\x01\x01\x12\x1a\n\x08\x65ndpoint\x18\x03 \x01(\tR\x08\x65ndpoint\x12*\n\x02\x61t\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x02\x61t\x12\x1e\n\x08trace_id\x18\x05 \x01(\x04H\x01R\x07traceId\x88\x01\x01\x12)\n\x04\x63ode\x18\x06 \x01(\x0e\x32\x10.google.rpc.CodeH\x02R\x04\x63ode\x88\x01\x01\x12@\n\x07request\x18\x07 \x03(\x0b\x32&.chalk.server.v1.AuditLog.RequestEntryR\x07request\x12\x43\n\x08response\x18\x08 \x03(\x0b\x32\'.chalk.server.v1.AuditLog.ResponseEntryR\x08response\x12\x13\n\x02ip\x18\t \x01(\tH\x03R\x02ip\x88\x01\x01\x1aR\n\x0cRequestEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12,\n\x05value\x18\x02 \x01(\x0b\x32\x16.google.protobuf.ValueR\x05value:\x02\x38\x01\x1aS\n\rResponseEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12,\n\x05value\x18\x02 \x01(\x0b\x32\x16.google.protobuf.ValueR\x05value:\x02\x38\x01\x42\x0e\n\x0c_descriptionB\x0b\n\t_trace_idB\x07\n\x05_codeB\x05\n\x03_ip\"\x15\n\x13GetAuditLogsRequest\"E\n\x14GetAuditLogsResponse\x12-\n\x04logs\x18\x01 \x03(\x0b\x32\x19.chalk.server.v1.AuditLogR\x04logs2p\n\x0c\x41uditService\x12`\n\x0cGetAuditLogs\x12$.chalk.server.v1.GetAuditLogsRequest\x1a%.chalk.server.v1.GetAuditLogsResponse\"\x03\x80}\x06\x42\x93\x01\n\x13\x63om.chalk.server.v1B\nAuditProtoP\x01Z\x12server/v1;serverv1\xa2\x02\x03\x43SX\xaa\x02\x0f\x43halk.Server.V1\xca\x02\x0f\x43halk\\Server\\V1\xe2\x02\x1b\x43halk\\Server\\V1\\GPBMetadata\xea\x02\x11\x43halk::Server::V1b\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Chalk
  module Server
    module V1
      AuditLog = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chalk.server.v1.AuditLog").msgclass
      GetAuditLogsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chalk.server.v1.GetAuditLogsRequest").msgclass
      GetAuditLogsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chalk.server.v1.GetAuditLogsResponse").msgclass
    end
  end
end
