# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: chalk/server/v1/audit.proto for package 'Chalk.Server.V1'

require 'grpc'
require 'chalk_ruby/protos/chalk/server/v1/audit_pb'

module Chalk
  module Server
    module V1
      module AuditService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'chalk.server.v1.AuditService'

          rpc :GetAuditLogs, ::Chalk::Server::V1::GetAuditLogsRequest, ::Chalk::Server::V1::GetAuditLogsResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
