# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: chalk/server/v1/authtesting.proto for package 'ChalkRuby'

require 'grpc'
require 'chalk/server/v1/authtesting_pb'

module ChalkRuby
  module AuthTestingService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'chalk.server.v1.AuthTestingService'

      rpc :GetUnauthedTestEndpoint, ::ChalkRuby::GetUnauthedTestEndpointRequest, ::ChalkRuby::GetUnauthedTestEndpointResponse
      rpc :GetAuthedTestEndpoint, ::ChalkRuby::GetAuthedTestEndpointRequest, ::ChalkRuby::GetAuthedTestEndpointResponse
      rpc :GetViewerTestEndpoint, ::ChalkRuby::GetViewerTestEndpointRequest, ::ChalkRuby::GetViewerTestEndpointResponse
      rpc :GetDataScientistTestEndpoint, ::ChalkRuby::GetDataScientistTestEndpointRequest, ::ChalkRuby::GetDataScientistTestEndpointResponse
      rpc :GetDeveloperTestEndpoint, ::ChalkRuby::GetDeveloperTestEndpointRequest, ::ChalkRuby::GetDeveloperTestEndpointResponse
      rpc :GetAdminTestEndpoint, ::ChalkRuby::GetAdminTestEndpointRequest, ::ChalkRuby::GetAdminTestEndpointResponse
      rpc :GetOwnerTestEndpoint, ::ChalkRuby::GetOwnerTestEndpointRequest, ::ChalkRuby::GetOwnerTestEndpointResponse
    end

    Stub = Service.rpc_stub_class
  end
end
