# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: chalk/server/v1/authtesting.proto for package 'Chalk.Server.V1'

require 'grpc'
require 'chalk_ruby/protos/chalk/server/v1/authtesting_pb'

module Chalk
  module Server
    module V1
      module AuthTestingService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'chalk.server.v1.AuthTestingService'

          rpc :GetUnauthedTestEndpoint, ::Chalk::Server::V1::GetUnauthedTestEndpointRequest, ::Chalk::Server::V1::GetUnauthedTestEndpointResponse
          rpc :GetAuthedTestEndpoint, ::Chalk::Server::V1::GetAuthedTestEndpointRequest, ::Chalk::Server::V1::GetAuthedTestEndpointResponse
          rpc :GetViewerTestEndpoint, ::Chalk::Server::V1::GetViewerTestEndpointRequest, ::Chalk::Server::V1::GetViewerTestEndpointResponse
          rpc :GetDataScientistTestEndpoint, ::Chalk::Server::V1::GetDataScientistTestEndpointRequest, ::Chalk::Server::V1::GetDataScientistTestEndpointResponse
          rpc :GetDeveloperTestEndpoint, ::Chalk::Server::V1::GetDeveloperTestEndpointRequest, ::Chalk::Server::V1::GetDeveloperTestEndpointResponse
          rpc :GetAdminTestEndpoint, ::Chalk::Server::V1::GetAdminTestEndpointRequest, ::Chalk::Server::V1::GetAdminTestEndpointResponse
          rpc :GetOwnerTestEndpoint, ::Chalk::Server::V1::GetOwnerTestEndpointRequest, ::Chalk::Server::V1::GetOwnerTestEndpointResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
