# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: chalk/server/v1/auth.proto for package 'ChalkRuby'

require 'grpc'
require 'chalk/server/v1/auth_pb'

module ChalkRuby
  module AuthService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'chalk.server.v1.AuthService'

      rpc :GetToken, ::ChalkRuby::GetTokenRequest, ::ChalkRuby::GetTokenResponse
      rpc :CreateLinkSession, ::ChalkRuby::CreateLinkSessionRequest, ::ChalkRuby::CreateLinkSessionResponse
      rpc :GetLinkSession, ::ChalkRuby::GetLinkSessionRequest, ::ChalkRuby::GetLinkSessionResponse
      rpc :UpdateLinkSession, ::ChalkRuby::UpdateLinkSessionRequest, ::ChalkRuby::UpdateLinkSessionResponse
    end

    Stub = Service.rpc_stub_class
  end
end
