# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: chalk/server/v1/auth.proto for package 'Chalk.Server.V1'

require 'grpc'
require 'chalk_ruby/protos/chalk/server/v1/auth_pb'

module Chalk
  module Server
    module V1
      module AuthService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'chalk.server.v1.AuthService'

          rpc :GetToken, ::Chalk::Server::V1::GetTokenRequest, ::Chalk::Server::V1::GetTokenResponse
          rpc :CreateLinkSession, ::Chalk::Server::V1::CreateLinkSessionRequest, ::Chalk::Server::V1::CreateLinkSessionResponse
          rpc :GetLinkSession, ::Chalk::Server::V1::GetLinkSessionRequest, ::Chalk::Server::V1::GetLinkSessionResponse
          rpc :UpdateLinkSession, ::Chalk::Server::V1::UpdateLinkSessionRequest, ::Chalk::Server::V1::UpdateLinkSessionResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
