# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: chalk/server/v1/billing.proto for package 'ChalkRuby'

require 'grpc'
require 'chalk/server/v1/billing_pb'

module ChalkRuby
  module BillingService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'chalk.server.v1.BillingService'

      # GetNodesAndPods returns the nodes and pods for the team by default,
      # not just a single environment. To limit the scope, add filters to
      # the request object.
      rpc :GetNodesAndPods, ::ChalkRuby::GetNodesAndPodsRequest, ::ChalkRuby::GetNodesAndPodsResponse
      # GetUsageChart shows the Chalk credit usage between a provided start and
      # end period. The usage can be grouped by UsageChartPeriod for daily or
      # monthly usage, and by UsageChartGrouping for instance type or cluster usage.
      rpc :GetUsageChart, ::ChalkRuby::GetUsageChartRequest, ::ChalkRuby::GetUsageChartResponse
      # GetUtilizationRates returns the current utilization rates for all
      # instance types.
      rpc :GetUtilizationRates, ::ChalkRuby::GetUtilizationRatesRequest, ::ChalkRuby::GetUtilizationRatesResponse
    end

    Stub = Service.rpc_stub_class
  end
end
