# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: chalk/server/v1/billing.proto for package 'Chalk.Server.V1'

require 'grpc'
require 'chalk_ruby/protos/chalk/server/v1/billing_pb'

module Chalk
  module Server
    module V1
      module BillingService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'chalk.server.v1.BillingService'

          # GetNodesAndPodsUI returns the nodes and pods for the team by default,
          # not just a single environment. To limit the scope, add filters to
          # the request object.
          # Use this endpoint going forward; GetNodesAndPods should be deprecated because
          # it reuses PubSub types that are dangerous to update and are not intended for UI use.
          rpc :GetNodesAndPodsUI, ::Chalk::Server::V1::GetNodesAndPodsUIRequest, ::Chalk::Server::V1::GetNodesAndPodsUIResponse
          # GetNodesAndPods returns the nodes and pods for the team by default,
          # not just a single environment. To limit the scope, add filters to
          # the request object.
          rpc :GetNodesAndPods, ::Chalk::Server::V1::GetNodesAndPodsRequest, ::Chalk::Server::V1::GetNodesAndPodsResponse
          # GetUsageChart shows the Chalk credit usage between a provided start and
          # end period. The usage can be grouped by UsageChartPeriod for daily or
          # monthly usage, and by UsageChartGrouping for instance type or cluster usage.
          rpc :GetUsageChart, ::Chalk::Server::V1::GetUsageChartRequest, ::Chalk::Server::V1::GetUsageChartResponse
          # GetUtilizationRates returns the current utilization rates for all
          # instance types.
          rpc :GetUtilizationRates, ::Chalk::Server::V1::GetUtilizationRatesRequest, ::Chalk::Server::V1::GetUtilizationRatesResponse
          rpc :GetPodRequestCharts, ::Chalk::Server::V1::GetPodRequestChartsRequest, ::Chalk::Server::V1::GetPodRequestChartsResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
