# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chalk/server/v1/bootstrap.proto

require 'google/protobuf'

require 'chalk_ruby/protos/chalk/server/v1/environment_pb'
require 'chalk_ruby/protos/chalk/server/v1/team_pb'


descriptor_data = "\n\x1f\x63halk/server/v1/bootstrap.proto\x12\x0f\x63halk.server.v1\x1a!chalk/server/v1/environment.proto\x1a\x1a\x63halk/server/v1/team.proto\"\xbe\x01\n!BootstrapExtraSettingsEnvironment\x12\\\n\x08settings\x18\x01 \x03(\x0b\x32@.chalk.server.v1.BootstrapExtraSettingsEnvironment.SettingsEntryR\x08settings\x1a;\n\rSettingsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\x08R\x05value:\x02\x38\x01\"\xf4\x02\n\x16\x42ootstrapExtraSettings\x12K\n\x06global\x18\x01 \x03(\x0b\x32\x33.chalk.server.v1.BootstrapExtraSettings.GlobalEntryR\x06global\x12]\n\x0c\x65nvironments\x18\x02 \x03(\x0b\x32\x39.chalk.server.v1.BootstrapExtraSettings.EnvironmentsEntryR\x0c\x65nvironments\x1a\x39\n\x0bGlobalEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\x08R\x05value:\x02\x38\x01\x1as\n\x11\x45nvironmentsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12H\n\x05value\x18\x02 \x01(\x0b\x32\x32.chalk.server.v1.BootstrapExtraSettingsEnvironmentR\x05value:\x02\x38\x01\"\xcd\x02\n\x16ParsedBootstrapConfigs\x12+\n\x05teams\x18\x01 \x03(\x0b\x32\x15.chalk.server.v1.TeamR\x05teams\x12\x34\n\x08projects\x18\x02 \x03(\x0b\x32\x18.chalk.server.v1.ProjectR\x08projects\x12@\n\x0c\x65nvironments\x18\x03 \x03(\x0b\x32\x1c.chalk.server.v1.EnvironmentR\x0c\x65nvironments\x12>\n\x0cteam_invites\x18\x04 \x03(\x0b\x32\x1b.chalk.server.v1.TeamInviteR\x0bteamInvites\x12N\n\x0e\x65xtra_settings\x18\x05 \x01(\x0b\x32\'.chalk.server.v1.BootstrapExtraSettingsR\rextraSettingsB\x97\x01\n\x13\x63om.chalk.server.v1B\x0e\x42ootstrapProtoP\x01Z\x12server/v1;serverv1\xa2\x02\x03\x43SX\xaa\x02\x0f\x43halk.Server.V1\xca\x02\x0f\x43halk\\Server\\V1\xe2\x02\x1b\x43halk\\Server\\V1\\GPBMetadata\xea\x02\x11\x43halk::Server::V1b\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Chalk
  module Server
    module V1
      BootstrapExtraSettingsEnvironment = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chalk.server.v1.BootstrapExtraSettingsEnvironment").msgclass
      BootstrapExtraSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chalk.server.v1.BootstrapExtraSettings").msgclass
      ParsedBootstrapConfigs = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chalk.server.v1.ParsedBootstrapConfigs").msgclass
    end
  end
end
