# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: chalk/server/v1/builder.proto for package 'Chalk.Server.V1'

require 'grpc'
require 'chalk_ruby/protos/chalk/server/v1/builder_pb'

module Chalk
  module Server
    module V1
      module BuilderService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'chalk.server.v1.BuilderService'

          rpc :GetSearchConfig, ::Chalk::Server::V1::GetSearchConfigRequest, ::Chalk::Server::V1::GetSearchConfigResponse
          # Takes an existing (past) deployment and promotes the k8s resources / other things associated with it.
          # Useful for debugging in local development where the auto activation doesn't work b/c no pubsub.
          rpc :ActivateDeployment, ::Chalk::Server::V1::ActivateDeploymentRequest, ::Chalk::Server::V1::ActivateDeploymentResponse
          rpc :IndexDeployment, ::Chalk::Server::V1::IndexDeploymentRequest, ::Chalk::Server::V1::IndexDeploymentResponse
          # Intermediate step in the deployment activation process. Allows for partial migration to the new
          # go-api-server builder service.
          rpc :DeployKubeComponents, ::Chalk::Server::V1::DeployKubeComponentsRequest, ::Chalk::Server::V1::DeployKubeComponentsResponse
          # Takes an existing (past) deployment and re-creates the image associated with it,
          # publishing the image as 'new_image_tag'.
          rpc :RebuildDeployment, ::Chalk::Server::V1::RebuildDeploymentRequest, ::Chalk::Server::V1::RebuildDeploymentResponse
          # Triggers a new build with the source code from this deployment and deploys the result
          rpc :RedeployDeployment, ::Chalk::Server::V1::RedeployDeploymentRequest, ::Chalk::Server::V1::RedeployDeploymentResponse
          # Triggers a new build with the provided source code archive and deploys the result
          rpc :UploadSource, ::Chalk::Server::V1::UploadSourceRequest, ::Chalk::Server::V1::UploadSourceResponse
          rpc :GetDeploymentSteps, ::Chalk::Server::V1::GetDeploymentStepsRequest, ::Chalk::Server::V1::GetDeploymentStepsResponse
          rpc :GetDeploymentLogs, ::Chalk::Server::V1::GetDeploymentLogsRequest, ::Chalk::Server::V1::GetDeploymentLogsResponse
          rpc :GetClusterTimescaleDB, ::Chalk::Server::V1::GetClusterTimescaleDBRequest, ::Chalk::Server::V1::GetClusterTimescaleDBResponse
          rpc :GetClusterGateway, ::Chalk::Server::V1::GetClusterGatewayRequest, ::Chalk::Server::V1::GetClusterGatewayResponse
          rpc :GetClusterBackgroundPersistence, ::Chalk::Server::V1::GetClusterBackgroundPersistenceRequest, ::Chalk::Server::V1::GetClusterBackgroundPersistenceResponse
          rpc :CreateClusterTimescaleDB, ::Chalk::Server::V1::CreateClusterTimescaleDBRequest, ::Chalk::Server::V1::CreateClusterTimescaleDBResponse
          rpc :MigrateClusterTimescaleDB, ::Chalk::Server::V1::MigrateClusterTimescaleDBRequest, ::Chalk::Server::V1::MigrateClusterTimescaleDBResponse
          rpc :CreateClusterGateway, ::Chalk::Server::V1::CreateClusterGatewayRequest, ::Chalk::Server::V1::CreateClusterGatewayResponse
          rpc :CreateClusterBackgroundPersistence, ::Chalk::Server::V1::CreateClusterBackgroundPersistenceRequest, ::Chalk::Server::V1::CreateClusterBackgroundPersistenceResponse
          rpc :UpdateEnvironmentVariables, ::Chalk::Server::V1::UpdateEnvironmentVariablesRequest, ::Chalk::Server::V1::UpdateEnvironmentVariablesResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
