# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chalk/server/v1/builder.proto

require 'google/protobuf'

require 'chalk/auth/v1/permissions_pb'


descriptor_data = "\n\x1d\x63halk/server/v1/builder.proto\x12\x0f\x63halk.server.v1\x1a\x1f\x63halk/auth/v1/permissions.proto\"Q\n\x19\x41\x63tivateDeploymentRequest\x12\x34\n\x16\x65xisting_deployment_id\x18\x01 \x01(\tR\x14\x65xistingDeploymentId\"\x1c\n\x1a\x41\x63tivateDeploymentResponse\"N\n\x16IndexDeploymentRequest\x12\x34\n\x16\x65xisting_deployment_id\x18\x01 \x01(\tR\x14\x65xistingDeploymentId\"\x19\n\x17IndexDeploymentResponse\"S\n\x1b\x44\x65ployKubeComponentsRequest\x12\x34\n\x16\x65xisting_deployment_id\x18\x01 \x01(\tR\x14\x65xistingDeploymentId\"\x1e\n\x1c\x44\x65ployKubeComponentsResponse2\xe9\x02\n\x0e\x42uilderService\x12r\n\x12\x41\x63tivateDeployment\x12*.chalk.server.v1.ActivateDeploymentRequest\x1a+.chalk.server.v1.ActivateDeploymentResponse\"\x03\x80}\x0e\x12i\n\x0fIndexDeployment\x12\'.chalk.server.v1.IndexDeploymentRequest\x1a(.chalk.server.v1.IndexDeploymentResponse\"\x03\x80}\x0e\x12x\n\x14\x44\x65ployKubeComponents\x12,.chalk.server.v1.DeployKubeComponentsRequest\x1a-.chalk.server.v1.DeployKubeComponentsResponse\"\x03\x80}\x0c\x42\x8d\x01\n\x13\x63om.chalk.server.v1B\x0c\x42uilderProtoP\x01Z\x12server/v1;serverv1\xa2\x02\x03\x43SX\xaa\x02\x0f\x43halk.Server.V1\xca\x02\x0f\x43halk\\Server\\V1\xe2\x02\x1b\x43halk\\Server\\V1\\GPBMetadata\xea\x02\tChalkRubyb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module ChalkRuby
  ActivateDeploymentRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chalk.server.v1.ActivateDeploymentRequest").msgclass
  ActivateDeploymentResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chalk.server.v1.ActivateDeploymentResponse").msgclass
  IndexDeploymentRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chalk.server.v1.IndexDeploymentRequest").msgclass
  IndexDeploymentResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chalk.server.v1.IndexDeploymentResponse").msgclass
  DeployKubeComponentsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chalk.server.v1.DeployKubeComponentsRequest").msgclass
  DeployKubeComponentsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chalk.server.v1.DeployKubeComponentsResponse").msgclass
end
