# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: chalk/server/v1/builder.proto for package 'ChalkRuby'

require 'grpc'
require 'chalk/server/v1/builder_pb'

module ChalkRuby
  module BuilderService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'chalk.server.v1.BuilderService'

      # Takes an existing (past) deployment and promotes the k8s resources / other things associated with it.
      # Useful for debugging in local development where the auto activation doesn't work b/c no pubsub.
      rpc :ActivateDeployment, ::ChalkRuby::ActivateDeploymentRequest, ::ChalkRuby::ActivateDeploymentResponse
      rpc :IndexDeployment, ::ChalkRuby::IndexDeploymentRequest, ::ChalkRuby::IndexDeploymentResponse
      # Intermediate step in the deployment activation process. Allows for partial migration to the new
      # go-api-server builder service.
      rpc :DeployKubeComponents, ::ChalkRuby::DeployKubeComponentsRequest, ::ChalkRuby::DeployKubeComponentsResponse
    end

    Stub = Service.rpc_stub_class
  end
end
