# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: chalk/server/v1/cli.proto for package 'Chalk.Server.V1'

require 'grpc'
require 'chalk_ruby/protos/chalk/server/v1/cli_pb'

module Chalk
  module Server
    module V1
      module CommandLineInterfaceService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'chalk.server.v1.CommandLineInterfaceService'

          rpc :GetVersions, ::Chalk::Server::V1::GetVersionsRequest, ::Chalk::Server::V1::GetVersionsResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
