# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: chalk/server/v1/cli.proto for package 'ChalkRuby'

require 'grpc'
require 'chalk/server/v1/cli_pb'

module ChalkRuby
  module CommandLineInterfaceService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'chalk.server.v1.CommandLineInterfaceService'

      rpc :GetVersions, ::ChalkRuby::GetVersionsRequest, ::ChalkRuby::GetVersionsResponse
    end

    Stub = Service.rpc_stub_class
  end
end
