# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: chalk/server/v1/deploy.proto for package 'ChalkRuby'

require 'grpc'
require 'chalk/server/v1/deploy_pb'

module ChalkRuby
  module DeployService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'chalk.server.v1.DeployService'

      rpc :DeployBranch, ::ChalkRuby::DeployBranchRequest, ::ChalkRuby::DeployBranchResponse
      rpc :GetDeployment, ::ChalkRuby::GetDeploymentRequest, ::ChalkRuby::GetDeploymentResponse
      rpc :ListDeployments, ::ChalkRuby::ListDeploymentsRequest, ::ChalkRuby::ListDeploymentsResponse
      rpc :GetActiveDeployments, ::ChalkRuby::GetActiveDeploymentsRequest, ::ChalkRuby::GetActiveDeploymentsResponse
      rpc :SuspendDeployment, ::ChalkRuby::SuspendDeploymentRequest, ::ChalkRuby::SuspendDeploymentResponse
      rpc :ScaleDeployment, ::ChalkRuby::ScaleDeploymentRequest, ::ChalkRuby::ScaleDeploymentResponse
      rpc :TagDeployment, ::ChalkRuby::TagDeploymentRequest, ::ChalkRuby::TagDeploymentResponse
    end

    Stub = Service.rpc_stub_class
  end
end
