# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: chalk/server/v1/deploy.proto for package 'Chalk.Server.V1'

require 'grpc'
require 'chalk_ruby/protos/chalk/server/v1/deploy_pb'

module Chalk
  module Server
    module V1
      module DeployService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'chalk.server.v1.DeployService'

          rpc :DeployBranch, ::Chalk::Server::V1::DeployBranchRequest, ::Chalk::Server::V1::DeployBranchResponse
          rpc :GetDeployment, ::Chalk::Server::V1::GetDeploymentRequest, ::Chalk::Server::V1::GetDeploymentResponse
          rpc :ListDeployments, ::Chalk::Server::V1::ListDeploymentsRequest, ::Chalk::Server::V1::ListDeploymentsResponse
          rpc :GetActiveDeployments, ::Chalk::Server::V1::GetActiveDeploymentsRequest, ::Chalk::Server::V1::GetActiveDeploymentsResponse
          rpc :SuspendDeployment, ::Chalk::Server::V1::SuspendDeploymentRequest, ::Chalk::Server::V1::SuspendDeploymentResponse
          rpc :ScaleDeployment, ::Chalk::Server::V1::ScaleDeploymentRequest, ::Chalk::Server::V1::ScaleDeploymentResponse
          rpc :TagDeployment, ::Chalk::Server::V1::TagDeploymentRequest, ::Chalk::Server::V1::TagDeploymentResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
