# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: chalk/server/v1/flag.proto for package 'Chalk.Server.V1'

require 'grpc'
require 'chalk_ruby/protos/chalk/server/v1/flag_pb'

module Chalk
  module Server
    module V1
      module FeatureFlagService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'chalk.server.v1.FeatureFlagService'

          rpc :GetFeatureFlags, ::Chalk::Server::V1::GetFeatureFlagsRequest, ::Chalk::Server::V1::GetFeatureFlagsResponse
          rpc :SetFeatureFlag, ::Chalk::Server::V1::SetFeatureFlagRequest, ::Chalk::Server::V1::SetFeatureFlagResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
