# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: chalk/server/v1/flag.proto for package 'ChalkRuby'

require 'grpc'
require 'chalk/server/v1/flag_pb'

module ChalkRuby
  module FeatureFlagService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'chalk.server.v1.FeatureFlagService'

      rpc :GetFeatureFlags, ::ChalkRuby::GetFeatureFlagsRequest, ::ChalkRuby::GetFeatureFlagsResponse
      rpc :SetFeatureFlag, ::ChalkRuby::SetFeatureFlagRequest, ::ChalkRuby::SetFeatureFlagResponse
    end

    Stub = Service.rpc_stub_class
  end
end
