# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: chalk/server/v1/graph.proto for package 'ChalkRuby'

require 'grpc'
require 'chalk/server/v1/graph_pb'

module ChalkRuby
  module GraphService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'chalk.server.v1.GraphService'

      # GetFeatureSQL returns the feature SQLs for a given deployment.
      rpc :GetFeatureSQL, ::ChalkRuby::GetFeatureSQLRequest, ::ChalkRuby::GetFeatureSQLResponse
      rpc :GetFeaturesMetadata, ::ChalkRuby::GetFeaturesMetadataRequest, ::ChalkRuby::GetFeaturesMetadataResponse
      rpc :GetGraph, ::ChalkRuby::GetGraphRequest, ::ChalkRuby::GetGraphResponse
      # UpdateGraph uploads the protobuf graph for a given deployment.
      rpc :UpdateGraph, ::ChalkRuby::UpdateGraphRequest, ::ChalkRuby::UpdateGraphResponse
    end

    Stub = Service.rpc_stub_class
  end
end
