# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: chalk/server/v1/graph.proto for package 'Chalk.Server.V1'

require 'grpc'
require 'chalk_ruby/protos/chalk/server/v1/graph_pb'

module Chalk
  module Server
    module V1
      module GraphService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'chalk.server.v1.GraphService'

          # GetFeatureSQL returns the feature SQLs for a given deployment.
          rpc :GetFeatureSQL, ::Chalk::Server::V1::GetFeatureSQLRequest, ::Chalk::Server::V1::GetFeatureSQLResponse
          rpc :GetFeaturesMetadata, ::Chalk::Server::V1::GetFeaturesMetadataRequest, ::Chalk::Server::V1::GetFeaturesMetadataResponse
          rpc :GetGraph, ::Chalk::Server::V1::GetGraphRequest, ::Chalk::Server::V1::GetGraphResponse
          # UpdateGraph uploads the protobuf graph for a given deployment.
          rpc :UpdateGraph, ::Chalk::Server::V1::UpdateGraphRequest, ::Chalk::Server::V1::UpdateGraphResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
