# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: chalk/server/v1/kube.proto for package 'Chalk.Server.V1'

require 'grpc'
require 'chalk_ruby/protos/chalk/server/v1/kube_pb'

module Chalk
  module Server
    module V1
      module KubeService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'chalk.server.v1.KubeService'

          # GetPodStackTraceDump gets the stack trace dump from a single process running in a pod
          # The process can be specified either by name or process ID
          rpc :GetPodStackTraceDump, ::Chalk::Server::V1::GetPodStackTraceDumpRequest, ::Chalk::Server::V1::GetPodStackTraceDumpResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
