# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chalk/server/v1/log.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'


descriptor_data = "\n\x19\x63halk/server/v1/log.proto\x12\x0f\x63halk.server.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9c\x01\n\x08LogEntry\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n\x08severity\x18\x02 \x01(\tH\x00R\x08severity\x88\x01\x01\x12\x38\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n\x07message\x18\x04 \x01(\tR\x07messageB\x0b\n\t_severityB\x91\x01\n\x13\x63om.chalk.server.v1B\x08LogProtoP\x01Z\x12server/v1;serverv1\xa2\x02\x03\x43SX\xaa\x02\x0f\x43halk.Server.V1\xca\x02\x0f\x43halk\\Server\\V1\xe2\x02\x1b\x43halk\\Server\\V1\\GPBMetadata\xea\x02\x11\x43halk::Server::V1b\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Chalk
  module Server
    module V1
      LogEntry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chalk.server.v1.LogEntry").msgclass
    end
  end
end
