# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chalk/server/v1/metrics.proto

require 'google/protobuf'

require 'chalk_ruby/protos/chalk/auth/v1/permissions_pb'


descriptor_data = "\n\x1d\x63halk/server/v1/metrics.proto\x12\x0f\x63halk.server.v1\x1a\x1f\x63halk/auth/v1/permissions.proto\"\x88\x01\n GetOverviewSummaryMetricsRequest\x12$\n\x0brange_start\x18\x01 \x01(\tH\x00R\nrangeStart\x88\x01\x01\x12 \n\trange_end\x18\x02 \x01(\tH\x01R\x08rangeEnd\x88\x01\x01\x42\x0e\n\x0c_range_startB\x0c\n\n_range_end\"A\n\x15OverviewSummaryMetric\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n\x05value\x18\x02 \x01(\x02R\x05value\"e\n!GetOverviewSummaryMetricsResponse\x12@\n\x07metrics\x18\x01 \x03(\x0b\x32&.chalk.server.v1.OverviewSummaryMetricR\x07metrics2\x9a\x01\n\x0eMetricsService\x12\x87\x01\n\x19GetOverviewSummaryMetrics\x12\x31.chalk.server.v1.GetOverviewSummaryMetricsRequest\x1a\x32.chalk.server.v1.GetOverviewSummaryMetricsResponse\"\x03\x80}\x06\x42\x95\x01\n\x13\x63om.chalk.server.v1B\x0cMetricsProtoP\x01Z\x12server/v1;serverv1\xa2\x02\x03\x43SX\xaa\x02\x0f\x43halk.Server.V1\xca\x02\x0f\x43halk\\Server\\V1\xe2\x02\x1b\x43halk\\Server\\V1\\GPBMetadata\xea\x02\x11\x43halk::Server::V1b\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Chalk
  module Server
    module V1
      GetOverviewSummaryMetricsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chalk.server.v1.GetOverviewSummaryMetricsRequest").msgclass
      OverviewSummaryMetric = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chalk.server.v1.OverviewSummaryMetric").msgclass
      GetOverviewSummaryMetricsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chalk.server.v1.GetOverviewSummaryMetricsResponse").msgclass
    end
  end
end
