# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: chalk/server/v1/metrics.proto for package 'Chalk.Server.V1'

require 'grpc'
require 'chalk_ruby/protos/chalk/server/v1/metrics_pb'

module Chalk
  module Server
    module V1
      module MetricsService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'chalk.server.v1.MetricsService'

          rpc :GetOverviewSummaryMetrics, ::Chalk::Server::V1::GetOverviewSummaryMetricsRequest, ::Chalk::Server::V1::GetOverviewSummaryMetricsResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
