# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: chalk/server/v1/monitoring.proto for package 'Chalk.Server.V1'

require 'grpc'
require 'chalk_ruby/protos/chalk/server/v1/monitoring_pb'

module Chalk
  module Server
    module V1
      module MonitoringService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'chalk.server.v1.MonitoringService'

          rpc :TestPagerDutyIntegration, ::Chalk::Server::V1::TestPagerDutyIntegrationRequest, ::Chalk::Server::V1::TestPagerDutyIntegrationResponse
          rpc :AddPagerDutyIntegration, ::Chalk::Server::V1::AddPagerDutyIntegrationRequest, ::Chalk::Server::V1::AddPagerDutyIntegrationResponse
          rpc :DeletePagerDutyIntegration, ::Chalk::Server::V1::DeletePagerDutyIntegrationRequest, ::Chalk::Server::V1::DeletePagerDutyIntegrationResponse
          rpc :SetDefaultPagerDutyIntegration, ::Chalk::Server::V1::SetDefaultPagerDutyIntegrationRequest, ::Chalk::Server::V1::SetDefaultPagerDutyIntegrationResponse
          rpc :UpdatePagerDutyIntegration, ::Chalk::Server::V1::UpdatePagerDutyIntegrationRequest, ::Chalk::Server::V1::UpdatePagerDutyIntegrationResponse
          rpc :GetAllPagerDutyIntegrations, ::Chalk::Server::V1::GetAllPagerDutyIntegrationsRequest, ::Chalk::Server::V1::GetAllPagerDutyIntegrationsResponse
          rpc :GetPagerDutyIntegration, ::Chalk::Server::V1::GetPagerDutyIntegrationRequest, ::Chalk::Server::V1::GetPagerDutyIntegrationResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
