# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: chalk/server/v1/monitoring.proto for package 'ChalkRuby'

require 'grpc'
require 'chalk/server/v1/monitoring_pb'

module ChalkRuby
  module MonitoringService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'chalk.server.v1.MonitoringService'

      rpc :TestPagerDutyIntegration, ::ChalkRuby::TestPagerDutyIntegrationRequest, ::ChalkRuby::TestPagerDutyIntegrationResponse
      rpc :AddPagerDutyIntegration, ::ChalkRuby::AddPagerDutyIntegrationRequest, ::ChalkRuby::AddPagerDutyIntegrationResponse
      rpc :DeletePagerDutyIntegration, ::ChalkRuby::DeletePagerDutyIntegrationRequest, ::ChalkRuby::DeletePagerDutyIntegrationResponse
      rpc :SetDefaultPagerDutyIntegration, ::ChalkRuby::SetDefaultPagerDutyIntegrationRequest, ::ChalkRuby::SetDefaultPagerDutyIntegrationResponse
      rpc :UpdatePagerDutyIntegration, ::ChalkRuby::UpdatePagerDutyIntegrationRequest, ::ChalkRuby::UpdatePagerDutyIntegrationResponse
      rpc :GetAllPagerDutyIntegrations, ::ChalkRuby::GetAllPagerDutyIntegrationsRequest, ::ChalkRuby::GetAllPagerDutyIntegrationsResponse
      rpc :GetPagerDutyIntegration, ::ChalkRuby::GetPagerDutyIntegrationRequest, ::ChalkRuby::GetPagerDutyIntegrationResponse
    end

    Stub = Service.rpc_stub_class
  end
end
