# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chalk/server/v1/named_query.proto

require 'google/protobuf'

require 'chalk/auth/v1/permissions_pb'
require 'chalk/graph/v1/graph_pb'


descriptor_data = "\n!chalk/server/v1/named_query.proto\x12\x0f\x63halk.server.v1\x1a\x1f\x63halk/auth/v1/permissions.proto\x1a\x1a\x63halk/graph/v1/graph.proto\"@\n\x19GetAllNamedQueriesRequest\x12#\n\rdeployment_id\x18\x01 \x01(\tR\x0c\x64\x65ploymentId\"0\n\x1aGetNamedQueryByNameRequest\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\"^\n\x1bGetNamedQueryByNameResponse\x12?\n\rnamed_queries\x18\x01 \x03(\x0b\x32\x1a.chalk.graph.v1.NamedQueryR\x0cnamedQueries\"]\n\x1aGetAllNamedQueriesResponse\x12?\n\rnamed_queries\x18\x01 \x03(\x0b\x32\x1a.chalk.graph.v1.NamedQueryR\x0cnamedQueries\"+\n)GetAllNamedQueriesActiveDeploymentRequest\"m\n*GetAllNamedQueriesActiveDeploymentResponse\x12?\n\rnamed_queries\x18\x01 \x03(\x0b\x32\x1a.chalk.graph.v1.NamedQueryR\x0cnamedQueries2\xac\x03\n\x11NamedQueryService\x12u\n\x12GetAllNamedQueries\x12*.chalk.server.v1.GetAllNamedQueriesRequest\x1a+.chalk.server.v1.GetAllNamedQueriesResponse\"\x06\x90\x02\x01\x80}\x0b\x12\xa5\x01\n\"GetAllNamedQueriesActiveDeployment\x12:.chalk.server.v1.GetAllNamedQueriesActiveDeploymentRequest\x1a;.chalk.server.v1.GetAllNamedQueriesActiveDeploymentResponse\"\x06\x90\x02\x01\x80}\x0b\x12x\n\x13GetNamedQueryByName\x12+.chalk.server.v1.GetNamedQueryByNameRequest\x1a,.chalk.server.v1.GetNamedQueryByNameResponse\"\x06\x90\x02\x01\x80}\x0b\x42\x90\x01\n\x13\x63om.chalk.server.v1B\x0fNamedQueryProtoP\x01Z\x12server/v1;serverv1\xa2\x02\x03\x43SX\xaa\x02\x0f\x43halk.Server.V1\xca\x02\x0f\x43halk\\Server\\V1\xe2\x02\x1b\x43halk\\Server\\V1\\GPBMetadata\xea\x02\tChalkRubyb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module ChalkRuby
  GetAllNamedQueriesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chalk.server.v1.GetAllNamedQueriesRequest").msgclass
  GetNamedQueryByNameRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chalk.server.v1.GetNamedQueryByNameRequest").msgclass
  GetNamedQueryByNameResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chalk.server.v1.GetNamedQueryByNameResponse").msgclass
  GetAllNamedQueriesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chalk.server.v1.GetAllNamedQueriesResponse").msgclass
  GetAllNamedQueriesActiveDeploymentRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chalk.server.v1.GetAllNamedQueriesActiveDeploymentRequest").msgclass
  GetAllNamedQueriesActiveDeploymentResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chalk.server.v1.GetAllNamedQueriesActiveDeploymentResponse").msgclass
end
