# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: chalk/server/v1/named_query.proto for package 'ChalkRuby'

require 'grpc'
require 'chalk/server/v1/named_query_pb'

module ChalkRuby
  module NamedQueryService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'chalk.server.v1.NamedQueryService'

      rpc :GetAllNamedQueries, ::ChalkRuby::GetAllNamedQueriesRequest, ::ChalkRuby::GetAllNamedQueriesResponse
      rpc :GetAllNamedQueriesActiveDeployment, ::ChalkRuby::GetAllNamedQueriesActiveDeploymentRequest, ::ChalkRuby::GetAllNamedQueriesActiveDeploymentResponse
      rpc :GetNamedQueryByName, ::ChalkRuby::GetNamedQueryByNameRequest, ::ChalkRuby::GetNamedQueryByNameResponse
    end

    Stub = Service.rpc_stub_class
  end
end
