# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: chalk/server/v1/status.proto for package 'ChalkRuby'

require 'grpc'
require 'chalk/server/v1/status_pb'

module ChalkRuby
  module HealthService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'chalk.server.v1.HealthService'

      rpc :CheckHealth, ::ChalkRuby::CheckHealthRequest, ::ChalkRuby::CheckHealthResponse
    end

    Stub = Service.rpc_stub_class
  end
end
