# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: chalk/server/v1/status.proto for package 'Chalk.Server.V1'

require 'grpc'
require 'chalk_ruby/protos/chalk/server/v1/status_pb'

module Chalk
  module Server
    module V1
      module HealthService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'chalk.server.v1.HealthService'

          # If any checks fail, this request fails.
          rpc :CheckHealth, ::Chalk::Server::V1::CheckHealthRequest, ::Chalk::Server::V1::CheckHealthResponse
          # Return the actual health check values.
          rpc :GetHealth, ::Chalk::Server::V1::GetHealthRequest, ::Chalk::Server::V1::GetHealthResponse
          # Return collected cluster prometheus metrics
          rpc :GetClusterMetrics, ::Chalk::Server::V1::GetClusterMetricsRequest, ::Chalk::Server::V1::GetClusterMetricsResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
