# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: chalk/server/v1/team.proto for package 'ChalkRuby'

require 'grpc'
require 'chalk/server/v1/team_pb'

module ChalkRuby
  module TeamService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'chalk.server.v1.TeamService'

      rpc :GetEnv, ::ChalkRuby::GetEnvRequest, ::ChalkRuby::GetEnvResponse
      rpc :GetEnvironments, ::ChalkRuby::GetEnvironmentsRequest, ::ChalkRuby::GetEnvironmentsResponse
      rpc :GetAgent, ::ChalkRuby::GetAgentRequest, ::ChalkRuby::GetAgentResponse
      rpc :GetDisplayAgent, ::ChalkRuby::GetDisplayAgentRequest, ::ChalkRuby::GetDisplayAgentResponse
      rpc :GetTeam, ::ChalkRuby::GetTeamRequest, ::ChalkRuby::GetTeamResponse
      rpc :CreateTeam, ::ChalkRuby::CreateTeamRequest, ::ChalkRuby::CreateTeamResponse
      rpc :CreateProject, ::ChalkRuby::CreateProjectRequest, ::ChalkRuby::CreateProjectResponse
      rpc :CreateEnvironment, ::ChalkRuby::CreateEnvironmentRequest, ::ChalkRuby::CreateEnvironmentResponse
      rpc :GetAvailablePermissions, ::ChalkRuby::GetAvailablePermissionsRequest, ::ChalkRuby::GetAvailablePermissionsResponse
      rpc :CreateServiceToken, ::ChalkRuby::CreateServiceTokenRequest, ::ChalkRuby::CreateServiceTokenResponse
      rpc :DeleteServiceToken, ::ChalkRuby::DeleteServiceTokenRequest, ::ChalkRuby::DeleteServiceTokenResponse
      rpc :ListServiceTokens, ::ChalkRuby::ListServiceTokensRequest, ::ChalkRuby::ListServiceTokensResponse
      rpc :UpdateServiceToken, ::ChalkRuby::UpdateServiceTokenRequest, ::ChalkRuby::UpdateServiceTokenResponse
      rpc :InviteTeamMember, ::ChalkRuby::InviteTeamMemberRequest, ::ChalkRuby::InviteTeamMemberResponse
      rpc :ExpireTeamInvite, ::ChalkRuby::ExpireTeamInviteRequest, ::ChalkRuby::ExpireTeamInviteResponse
      rpc :ListTeamInvites, ::ChalkRuby::ListTeamInvitesRequest, ::ChalkRuby::ListTeamInvitesResponse
      rpc :UpsertFeaturePermissions, ::ChalkRuby::UpsertFeaturePermissionsRequest, ::ChalkRuby::UpsertFeaturePermissionsResponse
      rpc :UpdateScimGroupSettings, ::ChalkRuby::UpdateScimGroupSettingsRequest, ::ChalkRuby::UpdateScimGroupSettingsResponse
      #  rpc SetEnvironmentVariables(SetEnvironmentVariablesRequest) returns
      #  (SetEnvironmentVariablesResponse) {
      #    option (chalk.auth.v1.permission) = PERMISSION_DEPLOY_CREATE;
      #  }
      #
      rpc :GetTeamPermissions, ::ChalkRuby::GetTeamPermissionsRequest, ::ChalkRuby::GetTeamPermissionsResponse
    end

    Stub = Service.rpc_stub_class
  end
end
