# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: chalk/server/v1/team.proto for package 'Chalk.Server.V1'

require 'grpc'
require 'chalk_ruby/protos/chalk/server/v1/team_pb'

module Chalk
  module Server
    module V1
      module TeamService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'chalk.server.v1.TeamService'

          rpc :GetEnv, ::Chalk::Server::V1::GetEnvRequest, ::Chalk::Server::V1::GetEnvResponse
          rpc :GetEnvironments, ::Chalk::Server::V1::GetEnvironmentsRequest, ::Chalk::Server::V1::GetEnvironmentsResponse
          rpc :GetAgent, ::Chalk::Server::V1::GetAgentRequest, ::Chalk::Server::V1::GetAgentResponse
          rpc :GetDisplayAgent, ::Chalk::Server::V1::GetDisplayAgentRequest, ::Chalk::Server::V1::GetDisplayAgentResponse
          rpc :GetTeam, ::Chalk::Server::V1::GetTeamRequest, ::Chalk::Server::V1::GetTeamResponse
          rpc :CreateTeam, ::Chalk::Server::V1::CreateTeamRequest, ::Chalk::Server::V1::CreateTeamResponse
          rpc :CreateProject, ::Chalk::Server::V1::CreateProjectRequest, ::Chalk::Server::V1::CreateProjectResponse
          rpc :CreateEnvironment, ::Chalk::Server::V1::CreateEnvironmentRequest, ::Chalk::Server::V1::CreateEnvironmentResponse
          rpc :GetAvailablePermissions, ::Chalk::Server::V1::GetAvailablePermissionsRequest, ::Chalk::Server::V1::GetAvailablePermissionsResponse
          rpc :CreateServiceToken, ::Chalk::Server::V1::CreateServiceTokenRequest, ::Chalk::Server::V1::CreateServiceTokenResponse
          rpc :DeleteServiceToken, ::Chalk::Server::V1::DeleteServiceTokenRequest, ::Chalk::Server::V1::DeleteServiceTokenResponse
          rpc :ListServiceTokens, ::Chalk::Server::V1::ListServiceTokensRequest, ::Chalk::Server::V1::ListServiceTokensResponse
          rpc :UpdateServiceToken, ::Chalk::Server::V1::UpdateServiceTokenRequest, ::Chalk::Server::V1::UpdateServiceTokenResponse
          rpc :InviteTeamMember, ::Chalk::Server::V1::InviteTeamMemberRequest, ::Chalk::Server::V1::InviteTeamMemberResponse
          rpc :ExpireTeamInvite, ::Chalk::Server::V1::ExpireTeamInviteRequest, ::Chalk::Server::V1::ExpireTeamInviteResponse
          rpc :ListTeamInvites, ::Chalk::Server::V1::ListTeamInvitesRequest, ::Chalk::Server::V1::ListTeamInvitesResponse
          rpc :UpsertFeaturePermissions, ::Chalk::Server::V1::UpsertFeaturePermissionsRequest, ::Chalk::Server::V1::UpsertFeaturePermissionsResponse
          rpc :UpdateScimGroupSettings, ::Chalk::Server::V1::UpdateScimGroupSettingsRequest, ::Chalk::Server::V1::UpdateScimGroupSettingsResponse
          #  rpc SetEnvironmentVariables(SetEnvironmentVariablesRequest) returns
          #  (SetEnvironmentVariablesResponse) {
          #    option (chalk.auth.v1.permission) = PERMISSION_DEPLOY_CREATE;
          #  }
          #
          rpc :GetTeamPermissions, ::Chalk::Server::V1::GetTeamPermissionsRequest, ::Chalk::Server::V1::GetTeamPermissionsResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
