# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chalk/server/v1/timeserieschart.proto

require 'google/protobuf'

require 'google/protobuf/duration_pb'
require 'google/protobuf/timestamp_pb'


descriptor_data = "\n%chalk/server/v1/timeserieschart.proto\x12\x0f\x63halk.server.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\".\n\x07PointV2\x12\x19\n\x05value\x18\x01 \x01(\x01H\x00R\x05value\x88\x01\x01\x42\x08\n\x06_value\"l\n\x0cTimeSeriesV2\x12\x30\n\x06points\x18\x01 \x03(\x0b\x32\x18.chalk.server.v1.PointV2R\x06points\x12\x14\n\x05label\x18\x02 \x01(\tR\x05label\x12\x14\n\x05units\x18\x03 \x01(\tR\x05units\"\xd7\x01\n\x11TimeSeriesChartV2\x12\x14\n\x05title\x18\x01 \x01(\tR\x05title\x12\x35\n\x06series\x18\x02 \x03(\x0b\x32\x1d.chalk.server.v1.TimeSeriesV2R\x06series\x12\x35\n\x08x_series\x18\x03 \x03(\x0b\x32\x1a.google.protobuf.TimestampR\x07xSeries\x12>\n\rwindow_period\x18\x04 \x01(\x0b\x32\x19.google.protobuf.DurationR\x0cwindowPeriodB\x95\x01\n\x13\x63om.chalk.server.v1B\x14TimeserieschartProtoP\x01Z\x12server/v1;serverv1\xa2\x02\x03\x43SX\xaa\x02\x0f\x43halk.Server.V1\xca\x02\x0f\x43halk\\Server\\V1\xe2\x02\x1b\x43halk\\Server\\V1\\GPBMetadata\xea\x02\tChalkRubyb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module ChalkRuby
  PointV2 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chalk.server.v1.PointV2").msgclass
  TimeSeriesV2 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chalk.server.v1.TimeSeriesV2").msgclass
  TimeSeriesChartV2 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chalk.server.v1.TimeSeriesChartV2").msgclass
end
