# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: chalk/server/v1/topicpush.proto for package 'ChalkRuby'

require 'grpc'
require 'chalk/server/v1/topicpush_pb'

module ChalkRuby
  module TopicPushService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'chalk.server.v1.TopicPushService'

      rpc :ListJobs, ::ChalkRuby::ListJobsRequest, ::ChalkRuby::ListJobsResponse
      rpc :CreateJob, ::ChalkRuby::CreateJobRequest, ::ChalkRuby::CreateJobResponse
      rpc :UpdateJob, ::ChalkRuby::UpdateJobRequest, ::ChalkRuby::UpdateJobResponse
      rpc :DeleteJob, ::ChalkRuby::DeleteJobRequest, ::ChalkRuby::DeleteJobResponse
      rpc :GetJobByName, ::ChalkRuby::GetJobByNameRequest, ::ChalkRuby::GetJobByNameResponse
    end

    Stub = Service.rpc_stub_class
  end
end
