# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: chalk/server/v1/topicpush.proto for package 'Chalk.Server.V1'

require 'grpc'
require 'chalk_ruby/protos/chalk/server/v1/topicpush_pb'

module Chalk
  module Server
    module V1
      module TopicPushService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'chalk.server.v1.TopicPushService'

          rpc :ListJobs, ::Chalk::Server::V1::ListJobsRequest, ::Chalk::Server::V1::ListJobsResponse
          rpc :CreateJob, ::Chalk::Server::V1::CreateJobRequest, ::Chalk::Server::V1::CreateJobResponse
          rpc :UpdateJob, ::Chalk::Server::V1::UpdateJobRequest, ::Chalk::Server::V1::UpdateJobResponse
          rpc :DeleteJob, ::Chalk::Server::V1::DeleteJobRequest, ::Chalk::Server::V1::DeleteJobResponse
          rpc :GetJobByName, ::Chalk::Server::V1::GetJobByNameRequest, ::Chalk::Server::V1::GetJobByNameResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
