# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chalk/auth/v1/audit.proto

require 'google/protobuf'

require 'google/protobuf/descriptor_pb'


descriptor_data = "\n\x19\x63halk/auth/v1/audit.proto\x12\rchalk.auth.v1\x1a google/protobuf/descriptor.proto\"a\n\x0c\x41uditOptions\x12/\n\x05level\x18\x01 \x01(\x0e\x32\x19.chalk.auth.v1.AuditLevelR\x05level\x12 \n\x0b\x64\x65scription\x18\x02 \x01(\tR\x0b\x64\x65scription*V\n\nAuditLevel\x12\x1b\n\x17\x41UDIT_LEVEL_UNSPECIFIED\x10\x00\x12\x16\n\x12\x41UDIT_LEVEL_ERRORS\x10\x01\x12\x13\n\x0f\x41UDIT_LEVEL_ALL\x10\x02:V\n\x05\x61udit\x12\x1e.google.protobuf.MethodOptions\x18\xb1\xea\x01 \x01(\x0b\x32\x1b.chalk.auth.v1.AuditOptionsR\x05\x61udit\x88\x01\x01\x42\x85\x01\n\x11\x63om.chalk.auth.v1B\nAuditProtoP\x01Z\x0e\x61uth/v1;authv1\xa2\x02\x03\x43\x41X\xaa\x02\rChalk.Auth.V1\xca\x02\rChalk\\Auth\\V1\xe2\x02\x19\x43halk\\Auth\\V1\\GPBMetadata\xea\x02\x0f\x43halk::Auth::V1b\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Chalk
  module Auth
    module V1
      AuditOptions = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chalk.auth.v1.AuditOptions").msgclass
      AuditLevel = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chalk.auth.v1.AuditLevel").enummodule
    end
  end
end
