# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chalk/auth/v1/featurepermission.proto

require 'google/protobuf'


descriptor_data = "\n%chalk/auth/v1/featurepermission.proto\x12\rchalk.auth.v1\"\xb0\x01\n\x12\x46\x65\x61turePermissions\x12?\n\x04tags\x18\x01 \x03(\x0b\x32+.chalk.auth.v1.FeaturePermissions.TagsEntryR\x04tags\x1aY\n\tTagsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x36\n\x05value\x18\x02 \x01(\x0e\x32 .chalk.auth.v1.FeaturePermissionR\x05value:\x02\x38\x01*\x99\x01\n\x11\x46\x65\x61turePermission\x12\"\n\x1e\x46\x45\x41TURE_PERMISSION_UNSPECIFIED\x10\x00\x12\x1c\n\x18\x46\x45\x41TURE_PERMISSION_ALLOW\x10\x01\x12%\n!FEATURE_PERMISSION_ALLOW_INTERNAL\x10\x02\x12\x1b\n\x17\x46\x45\x41TURE_PERMISSION_DENY\x10\x03\x42\x91\x01\n\x11\x63om.chalk.auth.v1B\x16\x46\x65\x61turepermissionProtoP\x01Z\x0e\x61uth/v1;authv1\xa2\x02\x03\x43\x41X\xaa\x02\rChalk.Auth.V1\xca\x02\rChalk\\Auth\\V1\xe2\x02\x19\x43halk\\Auth\\V1\\GPBMetadata\xea\x02\x0f\x43halk::Auth::V1b\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Chalk
  module Auth
    module V1
      FeaturePermissions = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chalk.auth.v1.FeaturePermissions").msgclass
      FeaturePermission = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chalk.auth.v1.FeaturePermission").enummodule
    end
  end
end
