# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: chalk/engine/v2/offline_store_service.proto for package 'Chalk.Engine.V2'

require 'grpc'
require 'chalk_ruby/protos/chalk/engine/v2/offline_store_service_pb'

module Chalk
  module Engine
    module V2
      module OfflineStoreService
        # This service exposes endpoints for dealing with the offline store. It should never depend on the python graph.
        # v2 introduces two breaking changes:
        # Uses messages from engine.v2 instead of common.v1 (common is not meant for engine-specific messages)
        # Removes certain endpoints added and had to be immediately deprecated due to deprecation
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'chalk.engine.v2.OfflineStoreService'

          rpc :GetQueryLogEntries, ::Chalk::Engine::V2::GetQueryLogEntriesRequest, ::Chalk::Engine::V2::GetQueryLogEntriesResponse
          rpc :GetQueryValues, ::Chalk::Engine::V2::GetQueryValuesRequest, ::Chalk::Engine::V2::GetQueryValuesResponse
          rpc :GetFeatureValuesTimeSeriesChart, ::Chalk::Engine::V2::GetFeatureValuesTimeSeriesChartRequest, ::Chalk::Engine::V2::GetFeatureValuesTimeSeriesChartResponse
          rpc :GetFeatureValues, ::Chalk::Engine::V2::GetFeatureValuesRequest, ::Chalk::Engine::V2::GetFeatureValuesResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
